name: movie-svc

on:
  push:
    branches: [master, dev, develop]
    paths:
      - 'movie/**'

  pull_request:
    branches: [master, dev, develop]
    paths:
      - 'movie/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd movie && npm install && npm run test:ci